#!/bin/zsh

# ${HOME}/.zshrc: user profile for zsh (zsh(1))
# Author: Christian M. Todie <ctodie@coreweave.com>

# Export environment variables.
export GPG_TTY=$TTY
export DOTFILES_ZSH_DEBUG="${DOTFILES_ZSH_DEBUG:-0}"
export DOTFILES_ZSH_CACHE=$XDG_CACHE_HOME/zsh

autoload -U +X compinit && compinit -u

# Define named directories: ~w <=> Windows home directory on WSL.
[[ -z $dotfiles_win_home ]] || hash -d w=$dotfiles_win_home

BIN_DIR=~/.local/bin
if [[ ! -d $BIN_DIR ]]; then
  mkdir -p $BIN_DIR
fi

CACHE_DIR=${XDG_CACHE_HOME:-~/.cache}
if [[ ! -d $CACHE_DIR ]]; then
  mkdir -p $CACHE_DIR
fi

MAN_DIR=~/.local/man
if [[ ! -d $MAN_DIR ]]; then
  mkdir -p $MAN_DIR
fi

# Extend PATH.
path+=${BIN_DIR}
fpath+=${COMP_DIR}
manpath+=${MAN_DIR}


BOLD="$(tput bold 2>/dev/null || printf '')"
GREY="$(tput setaf 0 2>/dev/null || printf '')"
UNDERLINE="$(tput smul 2>/dev/null || printf '')"
RED="$(tput setaf 1 2>/dev/null || printf '')"
GREEN="$(tput setaf 2 2>/dev/null || printf '')"
YELLOW="$(tput setaf 3 2>/dev/null || printf '')"
BLUE="$(tput setaf 4 2>/dev/null || printf '')"
MAGENTA="$(tput setaf 5 2>/dev/null || printf '')"
NO_COLOR="$(tput sgr0 2>/dev/null || printf '')"

pinfo() {
  printf '%s\n' "${BOLD}${GREY}>${NO_COLOR} $*"
}

pwarn() {
  printf '%s\n' "${YELLOW}! $*${NO_COLOR}"
}

pdebug() {
 if (( ${DOTFILES_ZSH_DEBUG} > 0 )); then
  printf '%s\n' "${BLUE}# $*${NO_COLOR}"
 fi
}

perror() {
  printf '%s\n' "${RED}x $*${NO_COLOR}" >&2
}

pcompleted() {
  printf '%s\n' "${GREEN}✓${NO_COLOR} $*"
}

has() {
  command -v -- "$1" 1>/dev/null 2>&1
}

readable() {
  [[ -r "$1" ]]
}

detect_arch() {
  arch="$(uname -m | tr '[:upper:]' '[:lower:]')"
  printf '%s' "${arch}"
}

detect_os() {
  platform="$(uname -s | tr '[:upper:]' '[:lower:]')"
  printf '%s' "${platform}"
}

dedent() {
    local -n reference="$1"
    reference="$(echo "$reference" | sed 's/^[[:space:]]*//')"
}

download() {
  url="$1"
  base=$(basename "$url")
  file="${2-$base}"
  if has curl; then
    curl -fsSL -o $file $url && return 0 || rc=$?
    perror "Command failed (exit code $rc): ${BLUE}$@${NO_COLOR}"
    return $rc
  else
    perror "curl not found, please install curl."
    return 1
  fi
  perror "Command failed (exit code $rc): ${BLUE}${cmd}${NO_COLOR}"
  return $rc
}

unpack() {
  local archive=$1
  local bin_dir=$2
  local sudo=${3-}

  case "$archive" in
    *.tar.gz)
      mkdir -p "${bin_dir}"
      flags=$(test -n "${VERBOSE-}" && echo "-xzvf" || echo "-xzf")
      ${sudo} tar "${flags}" "${archive}" -C "${bin_dir}" --strip-components=1
      return 0
      ;;
    *.zip)
      flags=$(test -z "${VERBOSE-}" && echo "-qq" || echo "")
      UNZIP="${flags}" ${sudo} unzip "${archive}" -d "${bin_dir}"
      return 0
      ;;
  esac

  perror "Unknown package extension."
  printf "\n"
  return 1
}

# 'bare-metal' plugin system inspired by
# https://github.com/mattmc3/zsh_unplugged#question-how-do-i-load-my-plugins-with-hypersonic-speed-rocket

plugin-load() {
  local repo plugin_name plugin_dir initfile initfiles
  ZPLUGINDIR=${ZPLUGINDIR:-$DOTFILES_ZSH_CACHE/plugins}
  for repo in $@; do
    plugin_name=${repo:t}
    plugin_dir=$ZPLUGINDIR/$plugin_name
    initfile=$plugin_dir/$plugin_name.plugin.zsh
    if [[ ! -d $plugin_dir ]]; then
      pinfo "Cloning $repo"
      # try ssh first, fall back to https
      command git clone -q --depth 1 --recursive --shallow-submodules git@github.com:$repo.git $plugin_dir 2>/dev/null || \
      command git clone -q --depth 1 --recursive --shallow-submodules https://github.com/$repo $plugin_dir 2>/dev/null
    fi
    if [[ ! -e $initfile ]]; then
      initfiles=($plugin_dir/*.plugin.{z,}sh(N) $plugin_dir/*.{z,}sh{-theme,}(N))
      [[ ${#initfiles[@]} -gt 0 ]] || { pwarn>&2 "Plugin has no init file '$repo'." && continue }
      ln -s "${initfiles[1]}" "$initfile"
    fi
    fpath+=$plugin_dir
    (( $+functions[zsh-defer] )) && zsh-defer . $initfile > /dev/null || . $initfile
  done
}

plugin-compile() {
  ZPLUGINDIR=${ZPLUGINDIR:-$DOTFILES_ZSH_CACHE/plugins}
  autoload -U zrecompile
  local f
  for f in $ZPLUGINDIR/**/*.zsh{,-theme}(N); do
    pinfo "compiling $f"
    zrecompile -pq "$f"
  done
}

plugin-update () {
  ZPLUGINDIR=${ZPLUGINDIR:-$DOTFILES_ZSH_CACHE/plugins}
  for d in $ZPLUGINDIR/*/.git(/); do
    pinfo "Updating ${d:h:t}..."
    command git -C "${d:h}" pull --ff --recurse-submodules --depth 1 --rebase --autostash
  done
}

plugin-clean () {
  ZPLUGINDIR=${ZPLUGINDIR:-$DOTFILES_ZSH_CACHE/plugins}
  rm -rf $ZPLUGINDIR
}

plugin-list () {
  if ! [[ -d $ZPLUGINDIR ]]; then
    pinfo "no plugins installed."
  fi

  for d in $ZPLUGINDIR/*/.git; do
    command git -C "${d:h}" remote get-url origin
  done
}

plugin-help () {
  pinfo "Usage: ${BOLD}${GREEN}plugin${NO_COLOR} load|clean|list|update|compile"
}

_plugin() {
    local line state
    _arguments -C \
               "1: :->cmds" \
               "*::arg:->args"
    case "$state" in
        cmds)
            _values "plugin command" \
                    "load[Load a whitespace seperated list of plugins.]" \
                    "clean[Nuke your plugin cache.]" \
		    "list[List all registered plugins.]" \
		    "update[Update all plugins.]" \
		    "compile[compile existing plugins for rapid load.]"
            ;;
    esac
}

plugin () {
  subcommand=$1
  case $subcommand in
    "" | "-h" | "--help")
      plugin-help
      ;;
    *)
      shift
      plugin-${subcommand} $@
      if [ $? = 127 ]; then
        perror "$subcommand is not a known subcommand."
	      pinfo "  run plugin --help for a list of known commands."
	      exit 1
      fi
      ;;
  esac
}
compdef _plugin plugin

if ! has op; then
    wget -O ~/op.zip  https://cache.agilebits.com/dist/1P/op2/pkg/v2.2.0/op_linux_amd64_v2.2.0.zip > /dev/null 2>&1
    unzip ~/op.zip > /dev/null 2>&1
    sudo chmod +x op
    sudo mv op /usr/local/bin/
fi
eval "$(op completion zsh)"; compdef _op op

chezmoi apply ~/.local-macros
source ~/.local-macros

if op account list | grep coreweave > /dev/null; then
  op signin
else
  eval $(op account add --address coreweave.1password.com --email jfeldman@coreweave.com --signin)
fi

if [ -f "~/.config/gh/hosts.yml" ]; then
  echo "$(op item get gh_access_token --fields credential)" | gh auth login --with-token
  echo "gh authenticated"
fi

chezmoi apply --force
plugins+=(
    coreweave/dev-shell
    FFKL/s3cmd-zsh-plugin
    jfeldman325/dev-packages
    # anything loaded after this plugin gets deffered to background async execution
    romkatv/zsh-defer
    Aloxaf/fzf-tab
    zdharma-continuum/fast-syntax-highlighting
)

plugin load $plugins
unset plugins


# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots     # no special treatment for file names with a leading dot
setopt no_auto_menu  # require an extra TAB press to open the completion menu
setopt no_beep
setopt prompt_subst
setopt inc_append_history
setopt share_history
setopt hist_ignore_space
setopt no_nomatch
setopt interactive_comments
setopt hash_list_all
setopt complete_in_word
setopt noflowcontrol

# use emacs style line controls
bindkey -e

# Autoload functions.
autoload -Uz zmv

# Interactive Shell Environment Variables:
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=$XDG_CACHE_HOME/zsh-history
export CLICOLOR_FORCE=1la
export KEYTIMEOUT=1
export LIBRARY_LOG_TIMESTAMP=1
export PAGER="less -RF"

#export EDITOR=vim
if has code; then
  export EDITOR="$(which code) -w"
  sucode() {
    EDITOR="$(which code) -w" command -- sudo -e "$@"
  }
elif has nvim; then
  export EDITOR=nvim
elif has vim; then
  export EDITOR=vim
elif has emacs; then
  export EDITOR=emacs
elif has nano; then
  printf "${RED}WARNING:${NO_COLOR} setting nano as editor. Install a better editor -- ctodie.\n"
  export EDITOR=nano
fi

# TODO: requires bat, fix this later
# export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Do CoreWeave specific stuff
if [ -d /etc/coreweave ]; then
  # Hello, beastie...
  pinfo "CoreWeave - status: ${GREEN}OK${NO_COLOR}" #Todo: check if coreweave is actually OK

  export POETRY_VERSION=1.1.6
  export MINIKUBE_KUBERNETES_VERSION="v${KUBECTL_VERSION-}"
  export SKAFFOLD_DEFAULT_REPO="registry.gitlab.com/coreweave"

  export VAULT_ADDR="https://vault.int.coreweave.com:8200"
  export VAULT_SKIP_VERIFY=true

  if [ -d "$COREWEAVE_PLUGIN_ZSH_PATH" ]; then
    motd="$(${COREWEAVE_PLUGIN_ZSH_PATH}/src/motd.sh 2>/dev/null)"
    pinfo "${motd}"
  fi
fi

# k alias hack TODO: remember compdef load order
has kubectl && . <(kubectl completion zsh) && compdef k=kubectl

# github-cli
has gh && . <(gh completion -s zsh) && compdef _gh gh

# gitlab-cli
has glab && . <(glab completion -s zsh) && compdef _glab glab

# dotfile manager
has chezmoi && . <(chezmoi completion zsh) && compdef _chezmoi chezmoi

# 1password
has op && . <(op completion zsh) && compdef _op op

# Define aliases.
alias sudo='/usr/bin/sudo'
alias grep='grep --color=auto'
alias df="df -Tha --total"
alias du="du -ach"
alias free="free -mt"
alias ps="ps auxf"

if has s3cmd; then
	compdef s3="s3cmd"
	alias s3="s3cmd"
fi

exaflags='--links --icons --git --group --changed --time-style iso'
alias ls="$(has exa && printf 'exa' || printf 'ls') --group-directories-first --color=auto"
alias ll="${aliases[ls]:-ls} -l $(has exa && printf $exaflags)"
alias la="${aliases[ll]:-ll} -@ -a"
alias tree="$(has exa && printf 'exa --tree' || printf 'tree -C')"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C ${BIN_DIR}/vault vault


if [ ! $(ps ax | grep [s]sh-agent | wc -l) -gt 0 ]; then
  echo "starting ssh agent"
  export SSH_AUTH_SOCK=~/.ssh/ssh-agent.$HOSTNAME.sock
  eval "$(ssh-agent -a $SSH_AUTH_SOCK)"
else
  export SSH_AUTH_SOCK=~/.ssh/ssh-agent.$HOSTNAME.sock  
  export SSH_AGENT_PID=$(ps ax | grep [s]sh-agent | awk '{print $2}')
fi

if ! ssh-add -l > /dev/null; then
  ssh-add ~/.ssh/id_rsa
  echo "ssh key added"
fi

has starship && eval "$(starship init zsh)"

if [ ! -f $KUBECONFIG ]; then
  klogin
fi

echo """\x1B[1;31m⣿⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⢻⡟⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⣿
⣿⠀⠀⠀⠀⠀⠀⠀⢀⣀⠈⠿⠄⢀⣩⣤⠬⣤⣈⡛⠀⣰⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⣦⣶⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠀⣀⠉⠂⡠⢺⠋⢹⠀⠀⠀⡋⠙⡦⡈⠀⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣷⣶⣶⣾⣿⣿⣦⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⡤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠘⠿⠃⡰⠁⠈⠀⣈⡶⠤⢶⣁⠀⠡⠘⡄⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣮⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⣐⣤⠀⡇⠀⢸⡎⢸⠀⠀⠀⡏⢱⡇⠀⡇⠘⠙⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣾⣿⣿⣿⠿⠛⠛⠛⠻⣿⠿⢿⡿⠋⠁⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⢀⣀⡀⢡⠀⡇⠀⠙⠶⠦⢶⠋⠀⠁⢀⠃⣤⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠈⠀⠈⠀⠀⠀⢀⣀⣀⠀⠀⠙⣿⣿⣮⣀⠀⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠉⠛⠃⠀⠱⣴⡄⢈⠀⠀⠀⡅⣠⡷⠂⢄⡈⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠊⣉⣽⣿⣿⠀⣀⣤⠤⠤⠦⠀⠀⠀⠀⠚⢛⣯⣭⣍⡉⠀⠀⢿⣿⣿⣿⣷⣬⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠀⠀⠸⠟⠁⠠⣉⠛⠓⠒⠚⠛⠁⠰⣤⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠔⢉⣿⣿⣿⠀⠀⣴⣶⣶⡤⠀⡄⠀⠀⠀⠘⢿⣿⡿⠀⠀⠀⢸⣿⣿⣿⣿⣭⣁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠚⠁⠀⢠⠗⠀⠹⠢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⣾⣿⣿⣿⣿⠀⠀⠙⠛⠋⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⠟⡛⠛⢻⣭⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⢠⠃⠀⠀⠐⢄⠀⠀⠀⠀⠀⣰⠏⠀⠙⠓⣼⣿⣿⣿⣶⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⡤⠀⠴⡇⠀⠠⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡀⣿⣿⣿⣿⣿⢿⡄⠀⠀⠀⠀⠘⠾⠦⠖⠓⠊⠀⠀⠀⠀⠀⠀⠀⢠⣤⣴⣿⣿⣿⣿⣿⣍⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠀⠀⠠⣤⣀⠀⠷⠂⠀⠋⠀⠐⠟⠃⣠⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣰⣿⣿⣿⣿⣿⣧⣄⠀⠀⠀⠀⠀⠀⣀⣀⣤⣀⡀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣏⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⢀⣤⣤⠀⠙⠀⡡⢒⣭⠟⠛⠯⣍⡒⢄⠛⠁⢀⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⢿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠠⣭⣭⣭⣭⣭⠖⠀⠀⠀⠀⢀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠈⠙⠄⢀⢎⣼⡟⠃⠀⠀⠀⠘⡿⣦⠱⡀⠛⠓⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠈⠉⠉⠉⠀⠀⠀⠀⡠⠚⠁⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⣴⠷⣒⠄⣸⡞⠁⡇⠀⠀⠀⠀⠀⡇⠈⢿⡇⠠⠶⠶⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡐⣨⣿⣿⣿⣿⣿⠿⣿⣿⣿⣿⣿⣿⡏⠑⠢⢀⡀⠀⣀⣀⡠⠔⠊⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⢀⣀⣄⠄⢸⢷⡀⡇⠀⠀⠀⠀⠀⡇⣠⠿⠇⣠⣠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⡟⢩⣟⣿⣿⠀⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣳⡟⠻⣣⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠉⢁⣀⠀⠢⡻⢿⣀⠀⠀⠀⣸⡯⢋⠌⡀⠀⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡜⠁⣿⣿⣇⢠⣿⣿⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⡇⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠀⠀⠚⠃⣤⡈⠂⠭⠷⠶⠾⠥⠒⠁⠐⠷⠶⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⢀⠏⢠⣿⣿⣿⡜⣿⣿⣿⣿⣿⣷⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⣿⣿⣿⣿⣿⣿⣦⣀⡳⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠃⠀⢾⣷⠆⠀⡦⠀⠙⡿⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢈⣤⣾⣂⣸⣿⣿⣿⣿⣿⠉⠈⢿⣿⠛⢻⣿⣷⣶⣤⣤⣄⣀⣀⣤⣤⣶⣾⣿⣿⡟⠋⣹⡿⠃⠀⣼⣿⣿⣿⣦⣦⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⣿⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣈⣁⣀⣀⣇⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣤⣤⣤⣤⣤⣤⣴⣶⣾⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣄⣤⣿⣷⣿⣿⣩⣉⣩⣿⣿⣭⣭⣽⣿⣭⣭⣬⣽⣿⣿⣿⣦⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣿
"""